[package]
name = "terraform_parser"
version = "0.1.0"
edition = "2021"

[lib]
name = "terraform_parser"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
